### ISSUE TITLE
Cannot Push to Dokku Host because of fatal: invalid refspec

### ISSUE THREAD

**Issue by nerg4l** [dokku/ci-docker-image#5]
### How reproducible

Always

### Steps to Reproduce

When running the following deployment task on GitLab CI the step fails.

(Had to replace the real IP with `<IP>` as I'm not allow to share it.)

```
deploy:
  stage: deploy
  only:
    - master
  image: dokku/ci-docker-image
  variables:
    GIT_REMOTE_URL: ssh://dokku@<IP>:22/filesystem
  script:
    - dokku-deploy
  after_script:
    - dokku-unlock
```

#### Actual Results

```
Running with gitlab-runner 13.6.0 (8fa89735)
  on UraharaShop GitLab Runner Spb582uJ
Preparing the "docker" executor
00:01
Using Docker executor with image dokku/ci-docker-image ...
Pulling docker image dokku/ci-docker-image ...
Using docker image sha256:29211d9c54cdcdb726bc5d65fe63e9adf2c72e31dbb91662236f017a094b3299 for dokku/ci-docker-image with digest dokku/ci-docker-image@sha256:6a7b90df529ead62847771e933dc8b3a0d41b4ea90f83e82a49720c132b0f71d ...
Preparing environment
00:01
Running on runner-spb582uj-project-21553206-concurrent-0 via ubuntu-s-1vcpu-2gb-ams3-01...
Getting source from Git repository
Fetching changes with git depth set to 50...
Reinitialized existing Git repository in /builds/uraharashop/filesystem/.git/
Checking out a30771d8 as master...
Removing .cache/
Removing coverage.out
Removing report.xml
Skipping Git submodules setup
Executing "step_script" stage of the job script
00:01
$ dokku-deploy
Setting up SSH Key
Generating SSH_HOST_KEY from ssh-keyscan against <IP>:22
# <IP>:22 SSH-2.0-OpenSSH_8.2p1 Ubuntu-4ubuntu0.1
# <IP>:22 SSH-2.0-OpenSSH_8.2p1 Ubuntu-4ubuntu0.1
# <IP>:22 SSH-2.0-OpenSSH_8.2p1 Ubuntu-4ubuntu0.1
# <IP>:22 SSH-2.0-OpenSSH_8.2p1 Ubuntu-4ubuntu0.1
# <IP>:22 SSH-2.0-OpenSSH_8.2p1 Ubuntu-4ubuntu0.1
Adding SSH Key to ssh-agent
Agent pid 28
Identity added: /root/.ssh/id_rsa (/root/.ssh/id_rsa)
Pushing to Dokku Host
fatal: invalid refspec 'a30771d80c847a2c0e6fa67a26853b1f3d462998:refs/heads/'
Running after_script
00:02
Running after script...
$ dokku-unlock
Setting up SSH Key
Generating SSH_HOST_KEY from ssh-keyscan against <IP>:22
# <IP>:22 SSH-2.0-OpenSSH_8.2p1 Ubuntu-4ubuntu0.1
# <IP>:22 SSH-2.0-OpenSSH_8.2p1 Ubuntu-4ubuntu0.1
# <IP>:22 SSH-2.0-OpenSSH_8.2p1 Ubuntu-4ubuntu0.1
# <IP>:22 SSH-2.0-OpenSSH_8.2p1 Ubuntu-4ubuntu0.1
# <IP>:22 SSH-2.0-OpenSSH_8.2p1 Ubuntu-4ubuntu0.1
Adding SSH Key to ssh-agent
Agent pid 28
Identity added: /root/.ssh/id_rsa (/root/.ssh/id_rsa)
Unlocking Dokku deployment
load pubkey "/root/.ssh/id_rsa": invalid format
 !     Unable to remove deploy lock
Cleaning up file based variables
00:00
ERROR: Job failed: exit code 128
```

#### Expected Results

To receive `Job succeeded`.

## Environment Information

- `SSH_PRIVATE_KEY` is set as a protected Variable on GitLab Group level
- `master` is a protected branch

### How (deb/make/rpm) and where (AWS, VirtualBox, physical, etc.) was Dokku installed?:

Dokku was installed with ansible on a physical machine.

### Additional information

- It works fine with `ilyasemenov/gitlab-ci-git-push`
  ```
  deploy:
    stage: deploy
    image: ilyasemenov/gitlab-ci-git-push
    environment:
      name: filesystem
    only:
      - master
    script:
      - git-push ssh://dokku@<IP>:22/filesystem
  ```
